sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    bucket-name: pm-sky-take
    endpoint: oss-cn-shenzhen.aliyuncs.com
    # 主机1保存到secret
    access-key-secret:
    access-key-id: LTAI5t95soRxQ2u6uasP1BiY
