sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    bucket-name: pm-sky-take
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-secret: omZ3DFX0J3A6nnwB6AdtyUiY6ULQ3P
    access-key-id: LTAI5t95soRxQ2u6uasP1BiY

  redis:
    host: localhost
    port: 6379
    database: 0

